/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUICalculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbNumero2 = new javax.swing.JTextField();
        btoSoma = new javax.swing.JButton();
        btoSubtracao = new javax.swing.JButton();
        btoMultiplicacao = new javax.swing.JButton();
        btoDivisao = new javax.swing.JButton();
        txtbResultado = new javax.swing.JTextField();
        btoResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Primeiro Número:");

        txtbNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbNumero1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Primeiro Número:");

        btoSoma.setText("+");
        btoSoma.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btoSomaAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                btoSomaAncestorRemoved(evt);
            }
        });
        btoSoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoSomaMouseClicked(evt);
            }
        });
        btoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSomaActionPerformed(evt);
            }
        });

        btoSubtracao.setText("-");
        btoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSubtracaoActionPerformed(evt);
            }
        });

        btoMultiplicacao.setText("*");
        btoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoMultiplicacaoActionPerformed(evt);
            }
        });

        btoDivisao.setText("/");
        btoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoDivisaoActionPerformed(evt);
            }
        });

        btoResultado.setText("Resultado");
        btoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtbNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtbNumero2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btoResultado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btoSoma)
                    .addComponent(btoSubtracao)
                    .addComponent(btoMultiplicacao)
                    .addComponent(btoDivisao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoResultado))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoSomaActionPerformed

    private void btoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoSubtracaoActionPerformed

    private void btoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoMultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoMultiplicacaoActionPerformed

    private void btoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoDivisaoActionPerformed

    private void txtbNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbNumero1ActionPerformed

    private void btoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoResultadoActionPerformed

    private void btoSomaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btoSomaAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btoSomaAncestorMoved

    private void btoSomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoSomaMouseClicked
        // TODO add your handling code here:

        while (txtbNumero1.getText().isEmpty()) {
            txtbNumero1.setText(JOptionPane.showInputDialog("Digite um número valido: "));
        }
        while (txtbNumero2.getText().isEmpty()) {
            txtbNumero2.setText(JOptionPane.showInputDialog("Digite um número valido: "));
            
        }

        double numero1 = Double.parseDouble(txtbNumero1.getText());
        double numero2 = Double.parseDouble(txtbNumero2.getText());
        txtbResultado.setText(Double.toString(Calcular.somar(numero1, numero2)));

        System.out.println("quero somar!" + numero1);

        /* int resp = JOptionPane.showConfirmDialog(rootPane, "Você gostaria de somar?");
        String segundoValor = "....";
        if (resp == JOptionPane.YES_OPTION)
            segundoValor=JOptionPane.showInputDialog(rootPane, "Digite o Segundo Numero: ");
        
        JOptionPane.showMessageDialog(rootPane, segundoValor); */
    }//GEN-LAST:event_btoSomaMouseClicked

    private void btoSomaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btoSomaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btoSomaAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoDivisao;
    private javax.swing.JButton btoMultiplicacao;
    private javax.swing.JButton btoResultado;
    private javax.swing.JButton btoSoma;
    private javax.swing.JButton btoSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtbNumero1;
    private javax.swing.JTextField txtbNumero2;
    private javax.swing.JTextField txtbResultado;
    // End of variables declaration//GEN-END:variables
}
